### PR TITLE
Update to latest Peass version and Add eclipse gitignore

### PR DESCRIPTION
**Pull request by DaGeRe**
To be compatible with the latest Peass version, I update the version. Furthermore, I added the eclipse-created files to `.gitignore`.

### CODE REVIEW

**Comment by stro18** [comment]
Upgrading the version of Peass is not possible yet since the Peass fork is still on version 1.13.

Also, changes need to be commited to branch `develop` first.

**Comment by stro18** [comment]
Upgrading the version of Peass is not possible yet since the Peass fork is still on version 1.13.

Also, changes need to be commited to branch `develop` first.

**Comment by stro18** [comment]
Peass version was upgraded wit commit [d4db035](https://github.com/stro18/peass-ant/commit/d4db03597c3676c20e2b79b990bff675db5cc81d).

**Comment by stro18** [comment]
@DaGeRe Can you please recreate the pull request and target the develop branch instead? I changed the target branch in this pull request, but the changes were not updated.

**Comment by DaGeRe** [comment]
What do you mean by "the changes where not updated"? In https://github.com/stro18/peass-ant/pull/9/files, I see the changes like expected. 
I can only recreate the PR for develop if we change this one to main again, since two PRs to the same branch with the same content are not possible.

**Comment by stro18** [comment]
> What do you mean by "the changes where not updated"?

The upgrade of the Peass version should not be in the changes anymore since it is already implemented in the develop branch.

Since the integration pipeline isn't working yet: Can you please create a PR without the pipeline stuff?

**Pull request closed without merging**
